name: ebhc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.2.5
  firebase_messaging: ^14.2.0
  cloud_firestore: ^4.7.1
  cloud_functions: ^4.0.7
  firebase_crashlytics: ^3.3.5
  google_maps_flutter: ^2.1.12
  firebase_ui_auth: 1.1.7
  google_fonts: ^4.0.1
  fcm_config: ^3.5.1
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.2
  state_notifier: ^0.7.2+1
  freezed_annotation: ^2.2.0
  routemaster: ^1.0.1
  flutter_native_splash: ^2.2.12
  url_launcher: ^6.1.2
  shared_preferences: ^2.0.15
  qr_code_scanner: ^1.0.0
  badges: ^2.0.3
  flutter_fgbg: ^0.3.0
  json_annotation: 4.7.0
  syncfusion_flutter_charts: ^21.1.38
  intl: ^0.18.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  http: ^0.13.6
  flutter_background_service: ^2.4.6
  workmanager: ^0.5.1
  background_fetch: ^1.2.1
  talker: ^3.1.1
  talker_flutter: ^3.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  flutter_launcher_icons: ^0.11.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - lib/i18n/

flutter_icons:
  image_path: "assets/images/eb-logo-nobranding-1152px.png"
  android: true
  ios: true
  background_color: "#FFFFFF"
  remove_alpha_ios: true

  # min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
