// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // throw UnsupportedError(
        //   'DefaultFirebaseOptions have not been configured for ios - '
        //   'you can reconfigure this by running the FlutterFire CLI again.',
        // );
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU-MZjirkbsNMKLlbq9d7ZLdBlnXirpGE',
    appId: '1:771460952772:web:7783c22a269ac997a7cf91',
    messagingSenderId: '771460952772',
    projectId: 'dev-proj-healthchecking-353609',
    authDomain: 'dev-proj-healthchecking-353609.firebaseapp.com',
    storageBucket: 'dev-proj-healthchecking-353609.appspot.com',
    measurementId: 'G-ML401C4FYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4aOGKPKGI0PgwOFBsZjDateXpQyPoXwc',
    appId: '1:771460952772:android:c3c3504f32cf193ea7cf91',
    messagingSenderId: '771460952772',
    projectId: 'dev-proj-healthchecking-353609',
    storageBucket: 'dev-proj-healthchecking-353609.appspot.com',
  );



  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoPh2Ui9PyK7m6kAlY32OhCOM_zHz6Lno',
    appId: '1:771460952772:ios:859a1d0ca0e4e766a7cf91',
    messagingSenderId: '771460952772',
    projectId: 'dev-proj-healthchecking-353609',
    storageBucket: 'dev-proj-healthchecking-353609.appspot.com',
  );


}
